cross-env:
  suffixid: None
dev:
  baseurl: None
  password: None
  user: None
int:
  baseurl: None
  password: None
  user: None
rec:
  baseurl: None
  password: None
  user: None
qat:
  baseurl: None
  password: None
  user: None
prd:
  baseurl: None
  password: None
  user: None