cross-env:
  suffixid: nuxeo/api/v1/id/
dev:
  baseurl: http://devpim/
  password: None
  user: None
int:
  baseurl: http://intpim/
  password: None
  user: None
rec:
  baseurl: https://rec-produits.groupe-pomona.fr/
  password: Ch@nt@L
  user: consult
qat:
  baseurl: None
  password: None
  user: None
prd:
  baseurl: https://produits.groupe-pomona.fr/
  password: Ch@nt@L
  user: consult